version: "3.5"

volumes:
  cache:
    driver: local

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
    volumes:
      - cache:/data

  db:
    image: postgres
    container_name: db
    ports:
      - "5432:$POSTGRES_PORT"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASS
      - POSTGRES_DB=$POSTGRES_DB
