version: "3.5"

services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:$POSTGRES_PORT"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASS
      - POSTGRES_DB=$POSTGRES_DB
