[app]
port = 7890
host = "0.0.0.0"

[database]
port = 5432
username = ''
password = ''
host = '0.0.0.0'
require_ssl = false
database_name = "newsletter"

[email_client]
# value in milliseconds
send_timeout_ms = 10000 # 10secs
# URL/URI of the email provider host
base_url = "localhost"
# sender email to be used to represent the `From` block of a email
sender_email = "test@gmail.com"
# Authorization token from the postmark or similar service
authorization = "my-secret-token"