[app]
port = 7890
domain = "http://some-domain"
host = "0.0.0.0"
hmac_secret = "super-long-and-secret-random-key-needed-to-verify-message-integrity"

[redis]
host = "0.0.0.0"
port = 6379
username = "redis"
password = "redis"

[database]
port = 5432
username = ''
password = ''
host = '0.0.0.0'
require_ssl = false
database_name = "newsletter"

[email_client]
# value in milliseconds
send_timeout_ms = 10000 # 10secs
# URL/URI of the email provider host
base_url = "some-email-provider-domain"
# sender email to be used to represent the `From` block of a email
sender_email = "test@gmail.com"
# Authorization token from the postmark or similar service
authorization = "my-secret-token"